name: GitHub Pages Build and Deploy

on:
  push:
    branches:
      - main # Adjust if your default branch is not `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Set your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run build script
      run: node build.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
